language: java
jdk:
- oraclejdk16
services:
- docker
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
#install:
#  - mvn clean package -P docker
#  - docker images
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  - docker tag click-count:latest $DOCKER_USERNAME/click-count
#  - docker push $DOCKER_USERNAME/click-count
script: skip
deploy:
  - provider: script
    script: echo "coucou deploy"
    on:
      branch: main
env:
  global:
  - secure: gigVe0jdhiNF78xC8U9rZYsp7tu/l3tmF9yZVlcRpFxOAdxPDMI5JiWAGHE3J96qr66Gf5nLThENsJvdyZrA1XEFrGXnfjR5xfsr71eYDsY9M+/9cMRvJYfiojc+TLJkTYCoX9PLmx1WDzCaTNIYbTAfEfcgK8aTWn6++jkDZaGXvnau1rZf0Ek6tkiFIs127yO+j90go5rH4+5AM/iuQwyjs0TYGwJzynWfjrxt4o0fEXISiSkSwzf5KIIy6ldQd0nNjhUoA83ceB5Jkf1OMNCMGP68uHb+QSXkxWe4MCOVL2vMBWF+loL/tyNId8UTAchhCWzK5M0FQ5uqjQUIxUhd4JjZxB4rk2NezSi/snmjIugsvPGdH0Nomia6VKHw0g6VKAV5HjmSdbxS/thlOGVFtE5iH1Su9n0UzE4rXMNWd46sokdmThDAtvzJ3w2OSpibFAqxX2OJ6b6UDO7eCri0otwL97g06h2Uf3DN8k6mDDgotLr/TSLKsD6Ehe0z6HQo0UhXsoNxHEgthpAqezuhpkhywSqYy0Mdpjeeym3G8jKl5dmmiW4PtH3N9OSyMHf014xbdQU7ETI4RAlYKUWqiNNj8pBkGGHu39cCbJGrfNhf/G5ztIMLuAir/0cwHrNkwJqHtyYMuTWQYdvgmJ3bjxLDUMfDYs7Kr8HBjko=
  - secure: WnE2bu7IS37euhOacq3mSTkWNCUW0sUz/JnIa9SqPU/uYUMH03WS18GMVXPKAV5hC0O59kS/9cKeZqnwlUURHLxw8tV+b3tuGnUe6N3VjHBWseCUkSk+siN6WLChuRd9CFInmAjJt6c+JvGiLBymKwZyUSN4jxrQpV4Wt4HpVPzjdISr2TADMQ/DKRcQbYb6yrsSMlYLJ/MRynW7u0d/FxN8Ue6vS50phBKBFP3q7TBesczWj9fsS+d0cOohXnCHuMKj/CA/kX+1tMsbHf/XD/plIbOP0doNllXMDVpnFu9uk1sg8gKKE61qA830swXavZnYJfpziVu0Y8q3yNqe5wc0SS7fOyl343sjIpeZvTkJDC/dG+uU1JpUslny+XDii/H4kKiGyDUYhuuJWZg3FIURUVT0Xey+EWW3iZITk/jlHlOuMN1wbAA7aMoWpQEEQkjGyKdwTeZwU6SfYWkDYkj7ecJbVc/yULpGBLu7/9ejTe3HK3IIwFKBY9TnABqE3IEOtuJRIj5Ho8HnfbRoqOJ8ZGhw10aM/vucAZmOLKnpVFiHgYZ4L8D/9dow+iifFziGqPsJWU3JerAcwUVNdg8atO/Nc1nk9XO3zbmFbMbX6iJH/bT8FTE14BuZId4dau1bqLkoAJocQ1PFXuw5TL1Xif/WijbhMXV/Txl0k3g=
