apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: click-count-${ENVIRONMENT}
  region: ${AWS_REGION}

nodeGroups:
  - name: default-nodegroup
    instanceType: t2.medium
    desiredCapacity: 3
